// Authenticate
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAIL = 'REFRESH_TOKEN_FAIL';

export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const AUTH_CHANGE_INFO = 'USER_CHANGE_INFO';

// Form
export const TOGGLE_FORM = 'TOGGLE_FORM';
export const OPEN_FORM = 'OPEN_FORM';
export const CLOSE_FORM = 'CLOSE_FORM';
export const IS_EDIT_ITEM_FORM = 'IS_EDIT_ITEM_FORM';
export const EDIT_ITEM_FORM_SUCCESS = 'EDIT_ITEM_FORM_SUCCESS';

// Work
export const ADD_WORK_SUCCESS = 'ADD_WORK_SUCCESS';
export const ADD_WORK_FAIL = 'ADD_WORK_FAIL';
export const GET_WORKS_SUCCESS = 'GET_WORKS_SUCCESS';
export const GET_WORKS_FAIL = 'GET_WORKS_FAIL';
export const EDIT_WORK_SUCCESS = 'EDIT_WORK_SUCCESS';
export const EDIT_WORK_FAIL = 'EDIT_WORK_FAIL';
export const DELETE_WORK_SUCCESS = 'DELETE_WORK_SUCCESS';
export const DELETE_WORK_FAIL = 'DELETE_WORK_FAIL';
export const CHANGE_PRIORITIZE_SUCCESS = 'CHANGE_PRIORITIZE_SUCCESS';
export const CHANGE_PRIORITIZE_FAIL = 'CHANGE_PRIORITIZE_FAIL';
export const CHANGE_TAB = 'CHANGE_TAB';
export const CHANGE_PAGE_TAB_PROCESS = 'CHANGE_PAGE_TAB_PROCESS';
export const CHANGE_PAGE_TAB_PENDING = 'CHANGE_PAGE_TAB_PENDING';
export const CHANGE_PAGE_TAB_END = 'CHANGE_PAGE_TAB_END';
export const END_SEARCH = 'END_SEARCH';

// CONTROL
export const SORT_AZ = 'SORT_AZ';
export const SORT_ZA = 'SORT_ZA';
export const SORT_STATUS_START = 'SORT_STATUS_START';
export const SORT_STATUS_WAITTING = 'SORT_STATUS_WAITTING';
export const SORT_STATUS_END = 'SORT_STATUS_END';
export const SORT_DEFAULT = 'SORT_DEFAULT';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';

// USER
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';
export const CHANGE_INFO_SUCCESS = 'CHANGE_INFO_SUCCESS';
export const CHANGE_INFO_FAIL = 'CHANGE_INFO_FAIL';

// STATISTICAL
export const STATISTICAL_WORK_PROCESS = 'STATISTICAL_WORK_PROCESS';
export const STATISTICAL_WORK_PENDING = 'STATISTICAL_WORK_PENDING';
export const STATISTICAL_WORK_END = 'STATISTICAL_WORK_END';
export const STATISTICAL_SET_WORKSTATUS = 'STATISTICAL_SET_WORKSTATUS';